// <auto-generated />
namespace EatOutByBI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Timekfjdkfj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Timekfjdkfj));
        
        string IMigrationMetadata.Id
        {
            get { return "201610241326553_Timekfjdkfj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
