// <auto-generated />
namespace DB_Testing3_EatOut.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testing321 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testing321));
        
        string IMigrationMetadata.Id
        {
            get { return "201610240848163_testing321"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
