// <auto-generated />
namespace DB_Testing3_EatOut.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MonthAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MonthAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201610200816400_MonthAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
