// <auto-generated />
namespace EatOutByBI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class first22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first22));
        
        string IMigrationMetadata.Id
        {
            get { return "201612211017414_first22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
