// <auto-generated />
namespace EatOutByBI.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addValidationBooking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addValidationBooking));
        
        string IMigrationMetadata.Id
        {
            get { return "201611151347315_addValidationBooking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
